In [6]:

import pandas as pd

events = pd.read_excel("care_flow_event_log.xlsx")
cases = pd.read_excel("care_flow_case_details.xlsx")
pathways = pd.read_excel("careflow_referance_pathway.xlsx")

print("Event Log:", events.shape)
print("Case Details:", cases.shape)
print("Reference Pathways:", pathways.shape)

Event Log: (10485, 8)
Case Details: (1500, 9)
Reference Pathways: (19, 4)

In [7]:
events.head()

,Case_ID,Activity_Name,Timestamp,Event_Order,Department,Triage_Priority,Shift,Doctor_ID
0,CF00001,Registration,20:22:00,1,General Emergency,Medium,Evening,DR006
1,CF00001,Triage,21:39:00,2,General Emergency,Medium,Evening,DR006
2,CF00001,Doctor Consultation,23:12:00,3,General Emergency,Medium,Evening,DR006
3,CF00001,Treatment,01:02:00,4,General Emergency,Medium,Evening,DR006
4,CF00001,Discharge,01:51:00,5,General Emergency,Medium,Evening,DR006

In [8]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10485 entries, 0 to 10484
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Case_ID          10485 non-null  object
 1   Activity_Name    10485 non-null  object
 2   Timestamp        10485 non-null  object
 3   Event_Order      10485 non-null  int64
 4   Department       10485 non-null  object
 5   Triage_Priority  10485 non-null  object
 6   Shift            10485 non-null  object
 7   Doctor_ID        10485 non-null  object
dtypes: int64(1), object(7)
memory usage: 655.4+ KB

In [9]:
events.head()

,Case_ID,Activity_Name,Timestamp,Event_Order,Department,Triage_Priority,Shift,Doctor_ID
0,CF00001,Registration,20:22:00,1,General Emergency,Medium,Evening,DR006
1,CF00001,Triage,21:39:00,2,General Emergency,Medium,Evening,DR006
2,CF00001,Doctor Consultation,23:12:00,3,General Emergency,Medium,Evening,DR006
3,CF00001,Treatment,01:02:00,4,General Emergency,Medium,Evening,DR006
4,CF00001,Discharge,01:51:00,5,General Emergency,Medium,Evening,DR006

In [ ]:
events.columns.tolist()# Check column names

['Case_ID',
 'Activity_Name',
 'Timestamp',
 'Event_Order',
 'Department',
 'Triage_Priority',
 'Shift',
 'Doctor_ID']

In [11]:
events.info()#Understand data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10485 entries, 0 to 10484
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Case_ID          10485 non-null  object
 1   Activity_Name    10485 non-null  object
 2   Timestamp        10485 non-null  object
 3   Event_Order      10485 non-null  int64
 4   Department       10485 non-null  object
 5   Triage_Priority  10485 non-null  object
 6   Shift            10485 non-null  object
 7   Doctor_ID        10485 non-null  object
dtypes: int64(1), object(7)
memory usage: 655.4+ KB

In [12]:
#numerical statistics
events.describe()

        Event_Order
count  10485.000000
mean       4.111588
std        2.183569
min        1.000000
25%        2.000000
50%        4.000000
75%        6.000000
max       10.000000

In [13]:
events["Activity_Name"].value_counts()#activity frequency

Activity_Name
Doctor Consultation    2816
Triage                 1788
Registration           1500
Treatment              1500
Discharge              1500
Blood Test              659
X-Ray                   657
CT Scan                  65
Name: count, dtype: int64

In [14]:
events.isnull().sum()   #Missing values

Case_ID            0
Activity_Name      0
Timestamp          0
Event_Order        0
Department         0
Triage_Priority    0
Shift              0
Doctor_ID          0
dtype: int64

In [15]:
events.duplicated().sum()   #duplicaterows

np.int64(0)

In [16]:
events["Case_ID"].nunique() #Unique patient cases

1500

In [17]:
events["Activity_Name"].nunique()   #Unique activities

8

In [18]:
events["Activity_Name"].value_counts()  #Activity frequency

Activity_Name
Doctor Consultation    2816
Triage                 1788
Registration           1500
Treatment              1500
Discharge              1500
Blood Test              659
X-Ray                   657
CT Scan                  65
Name: count, dtype: int64

In [19]:
events["Timestamp"] = pd.to_datetime(
    events["Timestamp"],
    errors="coerce"
)

print(events["Timestamp"].dtype)
print("Invalid timestamps:", events["Timestamp"].isna().sum())  #Convert timestamps to datetime

datetime64[ns]
Invalid timestamps: 10485

In [20]:
events = pd.read_excel("care_flow_event_log.xlsx")

events["Timestamp"].head(10) #Check the original timestamp value

0    20:22:00
1    21:39:00
2    23:12:00
3    01:02:00
4    01:51:00
5    19:18:00
6    19:23:00
7    19:51:00
8    20:09:00
9    21:25:00
Name: Timestamp, dtype: object

In [ ]:
events = pd.read_excel("care_flow_event_log.xlsx")

events["Timestamp"] = pd.to_datetime(
    events["Timestamp"].astype(str),
    format="%H:%M:%S",
    errors="coerce"
)

print(events["Timestamp"].head())
print("Invalid timestamps:", events["Timestamp"].isna().sum())#Convert time values

0   1900-01-01 20:22:00
1   1900-01-01 21:39:00
2   1900-01-01 23:12:00
3   1900-01-01 01:02:00
4   1900-01-01 01:51:00
Name: Timestamp, dtype: datetime64[ns]
Invalid timestamps: 0

In [22]:
events.columns.tolist() #Inspect the event log columns

['Case_ID',
 'Activity_Name',
 'Timestamp',
 'Event_Order',
 'Department',
 'Triage_Priority',
 'Shift',
 'Doctor_ID']

In [23]:
#Inspect the case details
cases = pd.read_excel("care_flow_case_details.xlsx")

print(cases.columns.tolist())
display(cases.head())

['Case_ID', 'Age', 'Sex', 'Triage_Priority', 'Department', 'Shift', 'Assigned_Doctor_ID', 'Arrival_Timestamp', 'Discharge_Status']

,Case_ID,Age,Sex,Triage_Priority,Department,Shift,Assigned_Doctor_ID,Arrival_Timestamp,Discharge_Status
0,CF00001,50,Not recorded,Medium,General Emergency,Evening,DR006,20:22:00,Discharged
1,CF00002,25,Male,High,General Emergency,Evening,DR013,19:18:00,Discharged
2,CF00003,19,Male,Low,Respiratory,Evening,DR016,20:20:00,Discharged
3,CF00004,37,Female,Medium,General Emergency,Night,DR009,22:33:00,Discharged
4,CF00005,36,Female,Medium,Orthopedics,Morning,DR011,13:00:00,Discharged

In [24]:
import pandas as pd

events = pd.read_excel("care_flow_event_log.xlsx")
cases = pd.read_excel("care_flow_case_details.xlsx")

print(events.head(10))
print(cases[["Case_ID", "Arrival_Timestamp"]].head())

   Case_ID        Activity_Name Timestamp  Event_Order         Department  \
0  CF00001         Registration  20:22:00            1  General Emergency
1  CF00001               Triage  21:39:00            2  General Emergency
2  CF00001  Doctor Consultation  23:12:00            3  General Emergency
3  CF00001            Treatment  01:02:00            4  General Emergency
4  CF00001            Discharge  01:51:00            5  General Emergency
5  CF00002         Registration  19:18:00            1  General Emergency
6  CF00002               Triage  19:23:00            2  General Emergency
7  CF00002  Doctor Consultation  19:51:00            3  General Emergency
8  CF00002            Treatment  20:09:00            4  General Emergency
9  CF00002            Discharge  21:25:00            5  General Emergency

  Triage_Priority    Shift Doctor_ID
0          Medium  Evening     DR006
1          Medium  Evening     DR006
2          Medium  Evening     DR006
3          Medium  Evening     DR006
4          Medium  Evening     DR006
5            High  Evening     DR013
6            High  Evening     DR013
7            High  Evening     DR013
8            High  Evening     DR013
9            High  Evening     DR013
   Case_ID Arrival_Timestamp
0  CF00001          20:22:00
1  CF00002          19:18:00
2  CF00003          20:20:00
3  CF00004          22:33:00
4  CF00005          13:00:00

In [28]:
events.groupby("Case_ID")["Event_Order"].apply(
    lambda s: s.is_monotonic_increasing
).value_counts()

Event_Order
True    1500
Name: count, dtype: int64

In [29]:
# Convert time-only values to timedeltas
events["Event_Time"] = pd.to_timedelta(events["Timestamp"].astype(str))
cases["Arrival_Time"] = pd.to_timedelta(cases["Arrival_Timestamp"].astype(str))

# Add arrival time to each event
events = events.merge(
    cases[["Case_ID", "Arrival_Time"]],
    on="Case_ID",
    how="left",
    validate="many_to_one"
)

# Sort by patient and event sequence
events = events.sort_values(
    ["Case_ID", "Event_Order"]
).reset_index(drop=True)

# Detect midnight crossings within each case
previous_time = events.groupby("Case_ID")["Event_Time"].shift()
crossed_midnight = events["Event_Time"] < previous_time

events["Day_Offset"] = (
    crossed_midnight.groupby(events["Case_ID"])
    .cumsum()
    .fillna(0)
    .astype(int)
)

# Build reconstructed timestamps relative to the arrival date
events["Timestamp_Reconstructed"] = (
    pd.Timestamp("2026-01-01")
    + events["Day_Offset"] * pd.Timedelta(days=1)
    + events["Event_Time"]
    - events["Arrival_Time"]
)

# Inspect the first case
display(
    events.loc[events["Case_ID"] == "CF00001", [
        "Case_ID", "Activity_Name", "Event_Order",
        "Timestamp", "Day_Offset", "Timestamp_Reconstructed"
    ]]
)

,Case_ID,Activity_Name,Event_Order,Timestamp,Day_Offset,Timestamp_Reconstructed
0,CF00001,Registration,1,20:22:00,0,2026-01-01 00:00:00
1,CF00001,Triage,2,21:39:00,0,2026-01-01 01:17:00
2,CF00001,Doctor Consultation,3,23:12:00,0,2026-01-01 02:50:00
3,CF00001,Treatment,4,01:02:00,1,2026-01-01 04:40:00
4,CF00001,Discharge,5,01:51:00,1,2026-01-01 05:29:00

In [30]:
#Calculate patient journey duration
journey = (
    events.groupby("Case_ID")["Timestamp_Reconstructed"]
    .agg(["min", "max"])
    .reset_index()
)

journey["Journey_Duration"] = (
    journey["max"] - journey["min"]
)

journey.head(10)

   Case_ID        min                 max Journey_Duration
0  CF00001 2026-01-01 2026-01-01 05:29:00  0 days 05:29:00
1  CF00002 2026-01-01 2026-01-01 02:07:00  0 days 02:07:00
2  CF00003 2026-01-01 2026-01-01 08:08:00  0 days 08:08:00
3  CF00004 2026-01-01 2026-01-01 10:14:00  0 days 10:14:00
4  CF00005 2026-01-01 2026-01-01 03:59:00  0 days 03:59:00
5  CF00006 2026-01-01 2026-01-01 04:07:00  0 days 04:07:00
6  CF00007 2026-01-01 2026-01-01 11:16:00  0 days 11:16:00
7  CF00008 2026-01-01 2026-01-01 09:04:00  0 days 09:04:00
8  CF00009 2026-01-01 2026-01-01 04:07:00  0 days 04:07:00
9  CF00010 2026-01-01 2026-01-01 07:54:00  0 days 07:54:00

In [31]:

journey["Journey_Duration"].describe()

count                         1500
mean        0 days 07:11:30.320000
std      0 days 03:04:14.961034451
min                0 days 00:57:00
25%                0 days 04:47:00
50%                0 days 07:00:00
75%                0 days 09:15:00
max                0 days 18:20:00
Name: Journey_Duration, dtype: object